<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>pc217953u20231e795.API</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="{BoundedContext}\interfaces\" />
    </ItemGroup>

</Project>
